### ISSUE TITLE
Create Docker image on Docker Hub

### ISSUE THREAD

**Issue by barkerd427** [prometheus-junkyard/mesos_exporter#1]
Could you create an image so we can just mount a config file in when we pull the image from the public Docker Hub? It looks like that would be possible from where it is right now, but I couldn't find this on the Hub.

**Comment by antonlindstrom** [comment]
@barkerd427 Ah, sure! I'll do that in a few moments.

Thanks!

**Comment by barkerd427** [comment]
Great! Thanks. I was going to, but I didn't want to step on your toes.

**Comment by antonlindstrom** [comment]
No worries, it's now available on the hub at https://registry.hub.docker.com/u/antonlindstrom/mesos-exporter/

Thanks again!

**Comment by barkerd427** [comment]
Works perfectly! docker run -d -v /root/config.json:/config.json -p
4000:4000 antonlindstrom/mesos-exporter

**Comment by antonlindstrom** [comment]
Awesome! I've added the command in the README for documentation.
