### ISSUE TITLE
Future of this repo / Replacing with https://github.com/prometheus/mesos_exporter?

### ISSUE THREAD

**Issue by discordianfish** [prometheus-junkyard/mesos_exporter#18]
Some time ago when I was working at Mesosphere I rewrote the mesos_exporter: https://github.com/mesosphere/mesos_exporter

See my mail from back then for details: https://groups.google.com/forum/#!searchin/prometheus-developers/mesos%2420johannes/prometheus-developers/8jVQlQIKo-M/gcN_P-S6AwAJ

Nowadays I'm not using mesos anymore, so might not be in the best position to decide this and need your input. I see the following options (or a mix of those)

1) Replace the repo with https://github.com/mesosphere/mesos_exporter
2) Remove this repo altogether to not mislead people in thinking this here is the best/official exporter
3) Find a new maintainer for this repo

Personally I would go for 1) for now but also find a new maintainer or, if we can't, remove the repo eventually.

What do you think?
/cc @antonlindstrom @tommyulfsparre @juliusv @keis @StephanErb @a-nldisr @brian-brazil @TNorden

**Comment by brian-brazil** [comment]
We should kick this repo to the junkyard anyway.

**Comment by antonlindstrom** [comment]
:+1: for Replacing this repo with the one from Mesosphere.

**Comment by keis** [comment]
It's not immediately obvious from either project so maybe some more familiar with the code highlight what the difference in exported metrics is? Is something missing from the other one?

**Comment by discordianfish** [comment]
@keis I don't think there is anything missing but since I'm not running mesos anymore (and barely did back then tbh), I might have missed something.
In general the code of the mesosphere exporter is cleaner / more idiomatic and the metrics where transformed to better fit into prometheus data model (having metrics with labels where it makes sense etc).

@brian-brazil What do you mean? Having no mesos repo at all? Or replacing this?

**Comment by brian-brazil** [comment]
https://github.com/prometheus-junkyard is where we put old code.

**Comment by discordianfish** [comment]
@brian-brazil OK but do you think we should fork/copy the mesosphere repo here? Or leave it at mesosphere where (probably) nobody will maintain it?

**Comment by brian-brazil** [comment]
It should only be part of the prometheus org if a core dev is willing to maintain it.

**Comment by tommyulfsparre** [comment]
LGTM! We are currently running the exporter as an aurora task (one per cluster) so this will not work us, but Im fine with that.

**Comment by keis** [comment]
Did a quick deploy of the other one with one master and one agent and it looks promising. It might needs some polish like tunable loglevels or etc. The only thing stopping us from using it is the licensing issue mesosphere/mesos_exporter#4

**Comment by discordianfish** [comment]
@keis That's a good point... I've reach out to someone from mesosphere, hopefully someone can add a license. Either way, I tend towards moving this repo to the junkyard since it probably doesn't make sense for me to maintain this given that I don't use mesos anymore.

**Comment by keis** [comment]
So it looks likes neither of these repos are actually maintained considering the recent commits on the mesosphere one is all from @discordianfish. Is the best option a fork?

**Comment by discordianfish** [comment]
@keis Correct, my initial plan was to fork the mesosphere one to the prometheus org. The question is simply if someone outside the prometheus org would be better suited to maintain it since I don't use mesos anymore.

**Comment by discordianfish** [comment]
Okay, given that the mesosphere exporter now has a license and can be used, I'll move this repo to the junkyard.

**Comment by brian-brazil** [comment]
I've kicked this repo over to junkyard. The Readme need updating.
